steps:

- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build'] # Or your specific build command

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install', '--save-dev', 'firebase-tools']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install', '-g', 'firebase-tools']

# - name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
#   args: ['deploy', '--token', '${_FIREBASE_TOKEN}']
#   env:
#     - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}' # Pass the token from the secret

# Deploy to Firebase Hosting
# - name: 'gcr.io/cloud-builders/firebase'
#   args: ['deploy', '--only', 'hosting', '--project', '${PROJECT_ID}']

- name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
  args: ['target:apply', 'hosting', 'dev_vms', 'dev-fb-autospotr-vms-hosting-b12w2']

- name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
  args: ['target:apply', 'hosting', 'dev_game', 'dev-fb-autospotr-game-hosting-b12w2']

- name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
  args: ['target']

- name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
  args: ['deploy', '--project', '${_FIREBASE_PROJECT_ID}', '--only', 'hosting:dev_vms']
  # env:
  #   - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}' # Pass the token from the secret

options:
  logging: CLOUD_LOGGING_ONLY