steps:

- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build'] # Or your specific build command

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install', '--save-dev', 'firebase-tools']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install', '-g', 'firebase-tools']

- name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
  args: ['deploy', '--token', '${_FIREBASE_TOKEN}']
  env:
    - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}' # Pass the token from the secret

# Deploy to Firebase Hosting
# - name: 'gcr.io/cloud-builders/firebase'
#   args: ['deploy', '--only', 'hosting', '--project', '${PROJECT_ID}']

- name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
  args: ['deploy', '--project', '${_FIREBASE_PROJECT_ID}', '--site', '${_FIREBASE_SITE_ID}', '--only', 'hosting']
  env:
    - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}' # Pass the token from the secret

options:
  logging: CLOUD_LOGGING_ONLY