steps:

- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build'] # Or your specific build command

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install', '--save-dev', 'firebase-tools']

- name: 'gcr.io/cloud-builders/npm'
  args: ['install', '-g', 'firebase-tools']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'firebase', 'deploy', '--project', '--token', '${_FIREBASE_TOKEN}']
  env:
    - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}' # Pass the token from the secret
    
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'firebase', 'deploy', '--project', '${_FIREBASE_PROJECT_ID}', '--site', '${_FIREBASE_SITE_ID}', '--only', 'hosting']
  env:
    - 'FIREBASE_TOKEN=${_FIREBASE_TOKEN}' # Pass the token from the secret

options:
  logging: CLOUD_LOGGING_ONLY